# Site Information
license:           "MIT"
license-url:       "https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE"
author:            "Blackrock Digital"

# Site Settings
baseurl:           ""

# Build settings
markdown:          kramdown
exclude:           [node_modules]

# Permalinks
permalink:        /blog/:title/

# Server
url:               https://themeauthority.com
enforce_ssl:       themeauthority.com
encoding:          UTF-8
host:              localhost
port:              9000

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-tidy

# Collections
collections:
  application:
    output:        true
    permalink:     /:collection/:title/
  games:
    output:        true
    permalink:     /:collection/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Blog Excerpt Separator
excerpt_separator: "<!--more-->"
