# Site Information
license:           "MIT"
license-url:       "https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE"
author:            "Blackrock Digital"

# Site Settings
baseurl:           ""

# Build settings
markdown:          kramdown
exclude:           [node_modules]

# Permalinks
permalink:        /blog/:title/

# Server
url:               https://themeauthority.com
enforce_ssl:       themeauthority.com
encoding:          UTF-8
host:              localhost
port:              9000

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-tidy

# Collections	# Collections
collections:	collections:
  themes:	
    output:        true	
    permalink:     /:collection/:title/	
  application:	  
    output:        true	    output:        
    permalink:     /:collection/:title/	   
  games:	  
    output:        true	    output:      
    permalink:     /:collection/:title/	    
  templates:	
    output:        true	
    permalink:     /:collection/:title/	
  snippets:	
    output:        true	
    permalink:     /:collection/:title/	
  guides:	
    output:        true	
    permalink:     /:collection/:title/	
  previews:	
    output:        true	
    permalink:     /:collection/:title/	
  premium:	
    output:        false

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Blog Excerpt Separator
excerpt_separator: "<!--more-->"
